export default {
	knowAndTech: 'pagging',
	lifestyle: 'pagging',
	healthAndLeisure: 'pagging',
	artAndDesign: 'pagging',
	joined: 'pagging',
	waitForJoin: 'pagging',
	managed: 'pagging',
	rejected: 'pagging',
	checking: 'pagging',
	recommend: 'pagging',
	applyList: 'pagging',
	groupActivity: 'pagging',
	groupMembers: 'pagging',
	groupAdmins: 'pagging',
	searchMembers: 'pagging',
	groupActivityForCheck: 'pagging',
	categoryTitles: 'non-pagging',
	groupInfo: 'non-pagging',
};
